Add guard to machida to ensure it is running single threaded
Prior to this commit, if machida was run with more one ponythread
it would result in a crash because of how the Python integration
currently functions.

This commit adds in a check to machida to ensure that it is running
in single threaded mode. If the check fail, machida will exit with
the following error:

```
Error: You must provide Machida with the '--ponythreads 1' argument to ensure it is single-threaded for the Python API or the cluster will crash.
```